### ISSUE TITLE
force refresh of svg.

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/phylografter#8]
I'm not sure if this is reproducible. I uploaded the tree for figure 1b of this study: http://reelab.net/phylografter/stree/svgView/568 
with the wrong rooting.  I went back to edit the record. Pasted that corrected rooting as a newick tree.  I still sees the wrong rooting, but if I:
1. cut  the newick tree out of the record,
2. save it as a local file
3. look at it in FigTree
   I see the correct rooting.

So it appears that phylografter is storing the correction to the newick, just not displaying it.

**Comment by rhr** [comment]
This is because phylografter doesn't monitor the text field containing the newick string for changes. When a tree is first uploaded, the newick string is converted into left-right indexed records in a node table. Currently there is no API for updating those indexes to reflect rerooting, branch rotating, etc.

**Comment by rhr** [comment]
I'm going to close this because it's addressed by the rooting issue.
